FROM python:3.11.2-bullseye

# ------------------ Ubuntu Setup ------------------ #
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -qy && apt upgrade -qy

# ------------------ Setup OpenCV ------------------ #
COPY . /app
WORKDIR /app
#RUN bash /opencv.sh
#ENTRYPOINT ["bash"]
